version: '3'
services:
  frontend:
    build: .
    image: acs-frontend
    container_name: acs-frontend
    stdin_open: true
    tty: true
    ports: 
      - "3000:8080"
    volumes:
      - .:/var/www/html/acs-frontend
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
